"""Generate portable booking pages from the authored booking sources."""
from pathlib import Path

source = Path(__file__).resolve().parent
root = source.parent
shell = (source / 'shell.html').read_text()
css = (root / 'website/css/tokens.css').read_text() + '\n' + (source / 'style.css').read_text()
js = '\n'.join((source / name).read_text() for name in ['model.js', 'view.js', 'app.js'])
result = shell.replace('/* BOOKING_STYLES */', css).replace('/* BOOKING_SCRIPTS */', js)
assert chr(0x2014) not in result
result = '<!-- Generated by booking/build.py. Edit the booking sources. -->\n' + result
for output in [source / 'index.html', root / 'dental-match-booking.html', root / '.lavish/dental-match-booking.html']:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(result)
print('Built four booking experiences and their portable review pages.')
