(function (root) {
  'use strict';
  const M = root.BookingModel;
  const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({ arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>', lock: '<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>', check: '<path d="m5 12 4 4L19 6"/>', phone: '<path d="M7 3 3 6c0 8 7 15 15 15l3-4-6-4-2 3c-3-1-4-2-5-5l3-2Z"/>', smile: '<path d="M3 10c4 12 14 12 18 0M7 5h.1M17 5h.1"/>', clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>' })[name] || ''}</svg>`;
  const logo = () => `<svg class="brand-logo" viewBox="88 13 164 118" role="img" aria-label="Dental Match"><text x="170" y="52" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="32" font-weight="500" letter-spacing="-1">dental</text><text x="170" y="96" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="49" font-weight="800" letter-spacing="-2">match</text><path d="M107 111Q170 132 233 111" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg>`;
  const button = (label, attrs = '', cls = 'primary') => `<button class="button ${cls}" ${attrs}>${e(label)}${cls === 'primary' ? icon('arrow') : ''}</button>`;
  const link = (route, label, cls = 'text-link') => `<a class="${cls}" href="#/${e(route)}">${e(label)}</a>`;
  const teethArt = (choice = 'All') => {
    const lit = { All: 16, '6+': 8, '3-5': 4, '2 or less': 2 }[choice];
    const shapes = Array.from({ length: 16 }, (_, i) => {
      const a = (205 + i * 8.7) * Math.PI / 180, x = 150 + 98 * Math.cos(a), y = 102 + 74 * Math.sin(a);
      return `<rect x="${x - 10}" y="${y - 13}" width="20" height="28" rx="8" transform="rotate(${i * 8.7 - 65} ${x} ${y})" fill="${i < lit ? 'var(--plum)' : 'white'}" stroke="${i < lit ? 'var(--plum)' : '#cabdde'}" stroke-width="1.5"/>`;
    }).join('');
    return `<svg class="teeth-art" viewBox="0 0 300 175" aria-hidden="true"><path d="M45 92C28-3 271-3 255 92" fill="none" stroke="#e0d5f0" stroke-width="37" stroke-linecap="round"/>${shapes}<path d="M88 118Q150 151 212 118" fill="none" stroke="var(--gold)" stroke-width="6" stroke-linecap="round"/></svg>`;
  };
  const notes = {
    teeth: 'Choose the closest answer. A dentist will assess your treatment options.',
    superBand: 'A super balance does not establish eligibility to access it. ATO approval and supporting evidence are required.',
    finance: 'This is an enquiry about options. It is not a finance application.',
    residency: 'Your answer helps our team understand which funding options to discuss.',
    work: 'Your answer helps the funding conversation. It does not determine approval.',
    state: 'This preview covers the six states in the reference form.'
  };
  const errorText = (key, s) => s.errors[key] ? `<p class="field-error" id="error-${e(key)}">${e(s.errors[key])}</p>` : '';
  function choices(key, s, visual = false) {
    const illustrated = visual && key === 'teeth';
    return `<fieldset class="choice-field" id="field-${key}" ${s.errors[key] ? `aria-describedby="error-${key}"` : ''}><legend class="${s.route === 'planner' ? 'field-label' : 'sr-only'}">${e(M.questions[key])}</legend><div class="choices ${['teeth', 'state'].includes(key) ? 'two-columns' : ''} ${illustrated ? 'illustrated' : ''}">${M.groups[key].map((answer, i) => `<label class="choice ${illustrated ? 'tooth-choice' : ''}"><input type="radio" name="${key}" value="${e(answer)}" ${s.v[key] === answer ? 'checked' : ''} ${s.errors[key] ? 'aria-invalid="true"' : ''}>${illustrated ? teethArt(answer) : ''}<span class="choice-copy"><strong>${e(answer)}</strong>${illustrated ? `<small>${['A full set', 'Six or more', 'Three to five', 'One or two'][i]}</small>` : ''}</span><span class="choice-check">${icon('check')}</span></label>`).join('')}</div>${errorText(key, s)}</fieldset>${notes[key] ? `<p class="field-note">${notes[key]}</p>` : ''}`;
  }
  function input(key, s) {
    const labels = { firstName: 'First name', lastName: 'Last name', email: 'Email address', phone: 'Phone number' };
    const placeholders = { firstName: 'Alex', lastName: 'Example', email: 'alex@example.com', phone: '0400 000 000' };
    const complete = { firstName: 'given-name', lastName: 'family-name', email: 'email', phone: 'tel' };
    return `<div class="field"><label for="field-${key}">${labels[key]}</label><input id="field-${key}" name="${key}" type="${key === 'email' ? 'email' : key === 'phone' ? 'tel' : 'text'}" autocomplete="${complete[key]}" maxlength="${key === 'email' ? 150 : key === 'phone' ? 25 : 80}" value="${e(s.v[key])}" placeholder="${placeholders[key]}" ${s.errors[key] ? `aria-invalid="true" aria-describedby="error-${key}"` : ''}>${errorText(key, s)}</div>`;
  }
  function consent(s) {
    return `<label class="consent" id="field-consent"><input type="checkbox" name="consent" ${s.v.consent ? 'checked' : ''} ${s.errors.consent ? 'aria-describedby="error-consent" aria-invalid="true"' : ''}><span>I am using sample details. I understand this preview sends no enquiry and makes no booking.</span></label>${errorText('consent', s)}<p class="field-note">Your answers stay on this page and are cleared when you reload. ${link('privacy', 'About this preview')}</p>`;
  }
  const contact = s => `<div class="field-pair">${input('firstName', s)}${input('lastName', s)}</div>${input('email', s)}${input('phone', s)}${consent(s)}`;
  function errorSummary(s) {
    return Object.keys(s.errors).length ? `<div class="error-summary" tabindex="-1" role="alert"><strong>Check these details to continue.</strong><ul>${Object.entries(s.errors).map(([key, message]) => `<li><a href="#field-${key}" data-error="${key}">${e(message)}</a></li>`).join('')}</ul></div>` : '';
  }
  function summaryRows(v) {
    return [['Missing / broken teeth', v.teeth, 'teeth'], ['Super balance', v.superBand, 'superBand'], ...M.fundingKeys(v).map(k => [{ finance: 'Payment plan', residency: 'Permanent resident', work: 'Work hours' }[k], v[k], k]), ['State', v.state, 'state'], ['Name', `${v.firstName} ${v.lastName}`.trim(), 'contact'], ['Email', v.email, 'contact'], ['Phone', v.phone, 'contact']];
  }
  function summary(s, editable = true) {
    const rows = summaryRows(s.v).flatMap(row => {
      if (s.variant !== 'conversation' || row[2] !== 'contact') return [row];
      if (row[0] === 'Name') return [['First name', s.v.firstName, 'firstName'], ['Last name', s.v.lastName, 'lastName']];
      return [[row[0], row[1], row[0] === 'Email' ? 'email' : 'phone']];
    });
    return `<dl class="review-list">${rows.map(([label, value, key]) => `<div><dt>${e(label)}</dt><dd>${e(value || 'Not added')}</dd>${editable ? `<button type="button" class="edit" data-edit="${key}" aria-label="Edit ${e(label)}">Edit</button>` : ''}</div>`).join('')}</dl>`;
  }
  function progress(s) {
    const group = ['teeth'].includes(s.route) ? 0 : ['superBand', 'finance', 'residency', 'work'].includes(s.route) ? 1 : ['state', 'contact', 'firstName', 'lastName', 'email', 'phone', 'consent'].includes(s.route) ? 2 : 3;
    return `<ol class="progress" aria-label="Enquiry stages">${['Your teeth', 'Funding', 'Your details', 'Next step'].map((name, i) => `<li class="${i <= group ? 'active' : ''}" ${i === group ? 'aria-current="step"' : ''}><span>${i < group ? icon('check') : i + 1}</span><small>${name}</small></li>`).join('')}</ol>`;
  }
  function intro(s) {
    return `<aside class="journey-intro"><p class="eyebrow">Dental implants · Your first step</p><h1>A consultation<br>starts with you.</h1><p class="lead">Tell us about your teeth and funding options. We’ll identify the next step for your enquiry.</p><div class="intro-smile">${teethArt(s.v.teeth || 'All')}</div><div class="intro-note">${icon('smile')}<p>Single implants, multiple teeth and full arch options, including All-on-4 and All-on-6.</p></div><p class="small-note">No treatment commitment. A dentist assesses what is right for you.</p></aside>`;
  }
  function formActions(s, last = false) {
    return `<div class="actions">${s.route !== 'teeth' ? button('Back', 'type="button" data-back', 'secondary') : '<span></span>'}${button(last ? 'See my next step' : 'Continue', 'type="submit"')}</div>`;
  }
  function step(s) {
    const key = s.route, keys = M.questionKeys(s.v, s.variant), index = keys.indexOf(key);
    const field = M.groups[key] ? choices(key, s, ['visual', 'card'].includes(s.variant)) : key === 'contact' ? contact(s) : key === 'consent' ? consent(s) : input(key, s);
    if (s.variant === 'conversation') {
      const history = keys.slice(0, index).filter(k => k !== 'consent').map(k => `<li><span>${e(M.questions[k])}</span><div><strong>${e(s.v[k])}</strong><button type="button" class="edit" data-edit="${k}" aria-label="Edit ${e(M.questions[k])}">Edit</button></div></li>`).join('');
      return `<div class="conversation-layout"><aside class="conversation-intro"><p class="eyebrow">A few questions. A clearer next step.</p><h1>Let’s work<br>through it.</h1><p class="lead">Your answers help us decide whether a clinic consultation or a call with our team should come next.</p>${history ? `<div class="answer-history"><h2>Your answers so far</h2><ol>${history}</ol></div>` : `<div class="conversation-empty">${icon('phone')}<p>This is a short form. If something needs explaining, our team can discuss it with you afterwards.</p></div>`}</aside><section class="form-panel conversation-panel">${progress(s)}<p class="eyebrow">Question ${index + 1}</p><h2 class="form-title">${e(M.questions[key])}</h2><form id="booking-form" novalidate>${errorSummary(s)}${field}${formActions(s)}</form></section></div>`;
    }
    return `<div class="journey-layout">${intro(s)}<section class="form-panel">${progress(s)}<p class="eyebrow">${index + 1} of ${keys.length} steps${M.lowSuper(s.v) ? ' · includes funding follow-up' : ''}</p><h2 class="form-title">${e(M.questions[key])}</h2><form id="booking-form" novalidate>${errorSummary(s)}${field}${formActions(s)}</form></section></div>`;
  }
  function planner(s) {
    return `<div class="planner-heading"><div><p class="eyebrow">Your consultation planner</p><h1>Put the pieces together.</h1><p class="lead">See the questions in one place. Funding questions appear only when they apply.</p></div><span class="planner-stamp">Dental implants<br>Consultation enquiry</span></div><div class="planner-layout"><form id="booking-form" novalidate>${errorSummary(s)}<section class="planner-section"><div class="section-number">1</div><div><h2>Your teeth</h2>${choices('teeth', s)}</div></section><section class="planner-section"><div class="section-number">2</div><div><h2>Your funding options</h2>${choices('superBand', s)}${M.fundingKeys(s.v).map(k => `<div class="funding-branch">${choices(k, s)}</div>`).join('')}</div></section><section class="planner-section"><div class="section-number">3</div><div><h2>Your location</h2>${choices('state', s)}</div></section><section class="planner-section"><div class="section-number">4</div><div><h2>Your contact details</h2>${contact(s)}</div></section><div class="planner-actions">${button('Review my enquiry', 'type="submit"')}</div></form><aside class="planner-aside"><p class="eyebrow">Your enquiry at a glance</p><h2>A starting point<br>for your consultation.</h2><div id="planner-summary">${miniSummary(s)}</div><p class="small-note">We use your answers to identify the next step. Clinical and funding approval come later.</p></aside></div>`;
  }
  function miniSummary(s) {
    return `<dl class="mini-summary">${[['Teeth', s.v.teeth], ['Super band', s.v.superBand], ['Location', s.v.state], ['Contact', `${s.v.firstName} ${s.v.lastName}`.trim()]].map(([label, value]) => `<div><dt>${e(label)}</dt><dd>${e(value || 'To be added')}</dd></div>`).join('')}</dl>`;
  }
  function review(s) {
    return `<section class="narrow-panel"><p class="eyebrow">Your consultation enquiry</p><h1>Everything look right?</h1><p class="lead">You can edit any answer before seeing your next step.</p><form id="booking-form" novalidate>${errorSummary(s)}${summary(s)}<div class="note">The next step is based on your answers. Dental treatment, finance and access to super require separate assessment.</div>${formActions(s, true)}</form></section>`;
  }
  const previewNote = text => `<div class="preview-note">${icon('clock')}<p><strong>Preview only.</strong> ${text}</p></div>`;
  const slotLabel = (s, id) => { const slot = s.slots.find(x => x.id === id); return slot ? `${slot.label} · ${slot.time}` : ''; };
  const timezone = state => ({ 'Western Australia (WA)': 'Australia/Perth', 'Queensland (QLD)': 'Australia/Brisbane', 'New South Wales (NSW)': 'Australia/Sydney', 'South Australia (SA)': 'Australia/Adelaide', 'Tasmania (TAS)': 'Australia/Hobart' })[state] || 'Australia/Melbourne';
  function clinic(s) {
    return `<div class="next-layout"><section><p class="eyebrow">Your next step · Clinic consultation</p><h1>Let’s arrange<br>a consultation.</h1><p class="lead">An implant consultation is the next referral step. The clinic will assess your teeth and discuss treatment and costs.</p>${previewNote('This is an example referral. No clinic has been matched and no enquiry has been sent.')}<div class="next-card"><span class="icon-disc">${icon('smile')}</span><div><p class="eyebrow">Example participating clinic</p><h2>Implant consultation</h2><p>${e(s.v.state)} · Consultation fee to be confirmed by the clinic</p></div></div>${button('Choose an example time', 'type="button" data-go="appointment"')}<p class="small-note action-note">Example times let you review the booking journey. A live booking link or calendar will supply real availability.</p></section><aside class="next-aside"><h2>What happens at the clinic?</h2><ol class="expectations"><li>Discuss your missing or broken teeth.</li><li>Assess suitability and explain treatment options.</li><li>Confirm costs, scans and possible funding routes.</li></ol><p class="small-note">A super balance does not confirm approval to access it.</p>${link('review', 'Review your answers')}</aside></div>`;
  }
  function appointment(s) {
    return `<section class="narrow-panel appointment-panel"><p class="eyebrow">Example implant consultation</p><h1>Find a time that works.</h1><p class="lead">${e(s.v.state)} · ${e(timezone(s.v.state))}</p>${previewNote('The following times are illustrative, not live availability.')}<form id="appointment-form" novalidate>${errorSummary(s)}<fieldset class="choice-field" id="field-slot"><legend class="field-label">Choose an example consultation time</legend><div class="slots">${s.slots.map(slot => `<label class="slot"><input type="radio" name="slot" value="${slot.id}" ${s.v.slot === slot.id ? 'checked' : ''}><span><strong>${e(slot.label)}</strong><small>${e(slot.time)}</small></span><span class="choice-check">${icon('check')}</span></label>`).join('')}</div>${errorText('slot', s)}</fieldset><div class="actions">${button('Back', 'type="button" data-go="clinic"', 'secondary')}${button(s.variant === 'card' ? 'Continue to card preview' : 'Review the booking step', 'type="submit"')}</div></form></section>`;
  }
  function card(s) {
    return `<div class="card-layout"><aside class="card-aside"><p class="eyebrow">Appointment details</p><h1>Your consultation,<br>set aside for you.</h1><div class="appointment-ticket"><p class="eyebrow">Example participating clinic</p><h2>Implant consultation</h2><p>${e(slotLabel(s, s.v.slot))}<br>${e(timezone(s.v.state))}</p><button class="edit" type="button" data-go="appointment">Change time</button></div><div class="amount"><span>Payment now</span><strong>A$0</strong></div><p>No appointment funds held. No no-show fee applies in this preview.</p><p class="small-note">A saved card is a commitment step. It does not reserve money or guarantee attendance.</p></aside><section class="secure-panel"><div class="secure-heading">${icon('lock')}<h2>Secure card setup</h2></div><p class="lead">The clinic’s secure payment page would collect your card directly.</p><div class="card-preview-label">Design preview · No payment provider connected</div><div class="card-fields" aria-label="Read-only example card"><div class="field-label">Card number</div><div class="dummy-input">4242 4242 4242 4242 <span>Example</span></div><div class="field-pair"><div><div class="field-label">Expiry</div><div class="dummy-input">12 / 30</div></div><div><div class="field-label">Security code</div><div class="dummy-input">•••</div></div></div></div><form id="card-form" novalidate>${errorSummary(s)}<label class="consent" id="field-policyConsent"><input type="checkbox" name="policyConsent" ${s.v.policyConsent ? 'checked' : ''}><span>I understand this example saves a card without an appointment hold, payment or no-show fee. This preview does not save a real card.</span></label>${errorText('policyConsent', s)}${button(s.v.demoCard ? 'Example card setup complete' : 'Try the card setup preview', 'type="button" data-simulate-card', 'secondary')}<p id="card-status" class="field-note" role="status">${s.v.demoCard ? 'Example complete. No card has been saved.' : 'Do not enter real card details. These fields are read-only.'}</p><div class="actions">${button('Back', 'type="button" data-go="appointment"', 'secondary')}${button('Review the booking step', 'type="submit"')}</div></form><button type="button" class="text-link card-help" data-go="booking-help">Prefer not to provide a card? Ask for booking help.</button></section></div>`;
  }
  function handoff(s) {
    return `<section class="narrow-panel"><p class="eyebrow">Clinic booking handoff</p><h1>Ready for the clinic’s booking page.</h1><p class="lead">The clinic confirms the appointment. Opening its booking page alone does not reserve your consultation.</p><div class="appointment-ticket"><h2>Example implant consultation</h2><p>${e(slotLabel(s, s.v.slot))}<br>${e(s.v.state)} · ${e(timezone(s.v.state))}</p><button type="button" class="edit" data-go="appointment">Change time</button>${s.variant === 'card' ? '<p class="field-note">Card setup simulated · A$0 paid · No funds held</p>' : ''}</div>${previewNote('No booking link is configured. No lead, appointment or card has been sent to a clinic.')}<button type="button" class="button primary" data-demo-handoff>Preview clinic handoff ${icon('arrow')}</button><p id="handoff-status" class="action-note" role="status"></p>${link('review', 'Edit your enquiry')}<button type="button" class="text-link reset-link" data-reset>Start another enquiry</button></section>`;
  }
  function team(s, assisted = false) {
    return `<div class="next-layout"><section><p class="eyebrow">${assisted ? 'Booking help' : 'Your next step · A call with Dental Match'}</p><h1>${assisted ? 'We can help with<br>the booking step.' : 'A conversation<br>before a consultation.'}</h1><p class="lead">${assisted ? 'Our team can explain the clinic’s card policy and discuss another booking option.' : 'Our team will clarify your implant needs and funding options before arranging a clinic consultation.'}</p>${previewNote('No enquiry has been sent. Try choosing a callback preference below.')}<form id="callback-form" novalidate>${errorSummary(s)}<fieldset class="choice-field" id="field-callback"><legend class="field-label">When would a call suit you?</legend><div class="choices">${['Morning · 9 am-12 pm', 'Afternoon · 12 pm-5 pm', 'No preference'].map(value => `<label class="choice"><input type="radio" name="callback" value="${value}" ${s.v.callback === value ? 'checked' : ''}><strong>${value}</strong><span class="choice-check">${icon('check')}</span></label>`).join('')}</div>${errorText('callback', s)}</fieldset><p class="field-note">Your local time · A preference, not a confirmed appointment.</p>${button('Preview my callback request', 'type="submit"')}</form>${assisted ? link('card', 'Return to the card preview') : link('review', 'Review your answers')}</section><aside class="next-aside"><span class="icon-disc">${icon('phone')}</span><h2>We’ll talk through</h2><ul class="expectations"><li>The teeth you want to replace.</li><li>The treatment you are exploring.</li><li>${assisted ? 'The clinic’s booking requirements.' : 'The funding questions that need clarification.'}</li></ul><p class="small-note">No finance or treatment approval is made by this form.</p></aside></div>`;
  }
  function callbackConfirmation(s) {
    return `<section class="narrow-panel confirmation"><span class="icon-disc">${icon('check')}</span><p class="eyebrow">Callback preview complete</p><h1>That is how your callback request will look.</h1><p class="lead">Our team would receive your enquiry and preferred call time.</p><dl class="review-list"><div><dt>Name</dt><dd>${e(s.v.firstName)} ${e(s.v.lastName)}</dd></div><div><dt>Phone</dt><dd>${e(s.v.phone)}</dd></div><div><dt>Preference</dt><dd>${e(s.v.callback)}</dd></div></dl>${previewNote('No request has been sent and no call is scheduled.')}<button type="button" class="button secondary" data-go="${s.assisted ? 'booking-help' : 'team'}">Change preference</button><button type="button" class="text-link reset-link" data-reset>Start another enquiry</button></section>`;
  }
  function followup(s) {
    return `<section class="narrow-panel confirmation"><span class="icon-disc">${icon('check')}</span><p class="eyebrow">Your next step · Enquiry follow-up</p><h1>Thank you.<br>We’ll review your enquiry.</h1><p class="lead">Our team will review your details and connect with you about a suitable next step.</p><p>No clinic consultation has been reserved.</p>${previewNote('This is the follow-up message for this example route. No enquiry has been sent.')}<div class="followup-details"><strong>${e(s.v.firstName)} ${e(s.v.lastName)}</strong><span>${e(s.v.email)}</span><span>${e(s.v.phone)}</span></div>${link('review', 'Review your answers')}<button type="button" class="text-link reset-link" data-reset>Start another enquiry</button></section>`;
  }
  function help() {
    return `<section class="narrow-panel information"><p class="eyebrow">Questions before you start</p><h1>What to expect.</h1>${[
      ['Which treatments is this for?', 'Dental implants, from one or a few missing teeth to partial and full arch treatment, including All-on-4 and All-on-6. A dentist recommends the treatment after assessment.'],
      ['Will I go straight to a clinic?', 'Your answers determine the next step. Some enquiries go to a clinic consultation, some need a call with Dental Match, and others go for follow-up.'],
      ['Do I need to know how to pay?', 'Answer using what you know. Lower super balance answers open a few payment-plan questions. Interest in finance is not an application or approval.'],
      ['Does a super balance mean I can use it?', 'No. Access depends on the applicable ATO requirements and approval, not just the balance. Our form does not decide that.'],
      ['Is a card required?', 'Only the fourth variation includes the example card step, after the clinic route and an appointment selection. Booking help is available if you do not want to continue with a card.'],
      ['Does this preview book anything?', 'No. Times, clinics and card details are examples. Enquiries remain on this page and are not sent anywhere.']
    ].map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}${link('resume', 'Return to my enquiry', 'button primary')}</section>`;
  }
  function privacy() {
    return `<section class="narrow-panel information"><p class="eyebrow">About this preview</p><h1>Your details in this review.</h1><p class="lead">Use sample contact details. This site does not submit enquiries, save a card or make appointments.</p><h2>What happens to the answers?</h2><p>They stay in page memory and clear when you reload or start again. No answers are stored in cookies, browser storage or a database. The page loads fonts from Google Fonts.</p><h2>Before the live form</h2><p>Dental Match needs its published privacy notice, consent wording and clinic-sharing arrangements. Live enquiry submission, clinic booking and provider-hosted card setup must be connected before the form is used in an ad campaign.</p><h2>Routing in this review</h2><p>The thresholds are illustrative commercial rules. They do not assess clinical suitability, approve finance or establish eligibility to access super.</p>${link('resume', 'Return to my enquiry', 'button primary')}</section>`;
  }
  function reviewer(s) {
    const result = M.route(s.v);
    return `<dialog id="review-dialog" aria-labelledby="review-title"><div class="dialog-header"><h2 id="review-title">Review the four booking experiences</h2><button type="button" class="close-dialog" data-close aria-label="Close review notes">×</button></div><p class="lead">Same questions. Different ways to complete the enquiry.</p><div class="rationale-grid">${Object.entries(M.variants).map(([id, v]) => `<article><p class="eyebrow">${v.number} · ${e(v.label)}</p><p>${v.rationale}</p><button type="button" class="text-link" data-variant="${id}">Try this version</button></article>`).join('')}</div><h3>Try the routing</h3><p>Load a sample enquiry at its review screen, then continue through the next step.</p><div class="fixture-actions">${button('Clinic route', 'type="button" data-fixture="clinic"', 'secondary')}${button('Team call', 'type="button" data-fixture="team"', 'secondary')}${button('Follow-up', 'type="button" data-fixture="followup"', 'secondary')}</div><div class="routing-rules"><h3>Illustrative routing rules</h3><ul><li><strong>Clinic:</strong> All / 6+ teeth, at least $20k in super and a listed state.</li><li><strong>Team:</strong> lower super band with finance interest, or 3-5 / 2 or less teeth.</li><li><strong>Follow-up:</strong> lower super band and no interest in finance.</li></ul><p>Residency and work answers inform the team call. They are not treated as universal lender requirements. Actual clinic coverage, treatment and funding thresholds still need approval.</p>${result ? `<p class="current-rule"><strong>Current enquiry:</strong> ${e(result.id)} · ${e(result.reason)}</p>` : ''}</div><h3>Card recommendation</h3><p>Use the clinic’s provider-hosted card setup after a real appointment is selected. A saved card is preferable to an authorisation hold for appointments booked ahead, because a hold expires and reduces available funds.</p><p>This review preserves the earlier A$0, no hold, no no-show charge arrangement. A card saved under that arrangement offers no financial protection against no-shows. Any future fee needs a stated amount, cancellation window, exceptions and explicit consent.</p><h3>What to measure</h3><p>Compare completed enquiries, correct referrals, attended consultations and card-step drop-off. Use the same Meta audience and questions to keep the comparison useful.</p><div class="review-links"><a href="https://aus.dentalmembersaustralia.com/#teeth" target="_blank" rel="noopener">Chosen question reference ↗</a><a href="https://agadgil-sap.github.io/dm-themes/" target="_blank" rel="noopener">Brand website ↗</a></div></dialog>`;
  }
  function page(s) {
    if (M.questionKeys(s.v, s.variant).includes(s.route)) return step(s);
    return ({ planner, review, clinic, appointment, card, handoff, team, followup, questions: help, privacy, 'booking-help': x => team(x, true), 'callback-confirmation': callbackConfirmation })[s.route]?.(s) || help();
  }
  function shell(s) {
    return `<div class="review-bar"><div class="wrap review-bar-inner"><span class="review-label">Booking review</span><div class="variant-switch" role="group" aria-label="Choose a booking variation">${Object.entries(M.variants).map(([id, v]) => `<button type="button" data-variant="${id}" aria-pressed="${s.variant === id}"><span>${v.number}</span><strong>${v.short}</strong></button>`).join('')}</div><button type="button" class="review-notes-button" data-review>Why these versions?</button></div></div><header class="booking-header wrap"><a class="brand-home" href="#/resume" aria-label="Return to my Dental Match enquiry">${logo()}</a><nav aria-label="Booking navigation">${link('questions', 'Questions')}${link('privacy', 'About this preview')}</nav></header><div class="sample-banner wrap"><span class="sample-dot"></span>Interactive review · Use sample details · No enquiries or bookings are sent</div><main class="wrap" id="main" tabindex="-1" data-route="${e(s.route)}" data-variant="${e(s.variant)}">${page(s)}</main><footer class="booking-footer wrap"><p>Dental Match · A matching service. Clinical advice comes from your dentist.</p><button class="text-link" type="button" data-reset>Start again</button></footer>${reviewer(s)}`;
  }
  root.BookingView = { e, shell, miniSummary, slotLabel, timezone };
})(window);
