(function (DM) {
  'use strict';
  const e = DM.escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  DM.icon = (name, cls = '') => {
    const shapes = {
      arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>', check: '<path d="m5 12 4 4L19 6"/>', plus: '<path d="M12 5v14M5 12h14"/>', close: '<path d="m6 6 12 12M18 6 6 18"/>', menu: '<path d="M4 7h16M4 12h16M4 17h16"/>',
      chat: '<path d="M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-8l-6 3v-3H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M7 9h10M7 13h7"/>',
      heart: '<path d="M12 20 4 12C-1 6 6 1 12 7c6-6 13-1 8 5Z"/>', clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', wallet: '<path d="M4 6h15v14H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h13v3M19 11h-6v5h6"/><path d="M15 13.5h.1"/>',
      leaf: '<path d="M4 19C1 8 8 2 21 3c1 13-5 18-13 16M5 20 15 9"/>', location: '<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
      tooth: '<path d="M12 5c-4-3-8-2-8 3 0 4 2 13 4 13 1 0 1-6 4-6s3 6 4 6c2 0 4-9 4-13 0-5-4-6-8-3Z"/>', teeth: '<path d="M4 5c-2 0-3 2-2 5l2 9c1 2 2 0 2-2s1-3 2-3 2 1 2 3 1 4 2 2l2-9c1-3-1-5-3-5L8 6ZM16 5c3-2 6-1 6 3 0 3-1 11-3 11-1 0-1-5-3-5"/>',
      smile: '<path d="M3 12c4 10 14 10 18 0"/><path d="M6 7h.1M18 7h.1" stroke-width="3"/>', match: '<path d="M3 13c4-8 8-8 12 0M9 13c4-8 8-8 12 0M5 17c5 5 9 5 14 0"/>', shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>', book: '<path d="M12 5c-4-2-7-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-3-1-6-1-10 1v15"/>'
    };
    return `<svg class="icon ${e(cls)}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${shapes[name] || shapes.check}</svg>`;
  };
  DM.logo = (cls = '') => `<svg class="brand-logo ${e(cls)}" viewBox="88 13 164 118" role="img" aria-label="Dental Match"><text x="170" y="52" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="32" font-weight="500" letter-spacing="-1">dental</text><text x="170" y="96" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="49" font-weight="800" letter-spacing="-2">match</text><path d="M107 111Q170 132 233 111" fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg>`;
  DM.link = (route, label, cls = '', extra = '') => `<a href="#${e(route)}" class="${e(cls)}" data-route="${e(route)}" data-lavish-action ${extra}>${label}</a>`;
  DM.button = (route, label = 'Explore my options', secondary = false, extra = '') => DM.link(route, `${e(label)}${DM.icon('arrow')}`, `button ${secondary ? 'button-secondary' : 'button-primary'}`, extra);
  DM.sectionHead = (eyebrow, title, body = '', cls = '') => `<div class="section-head ${e(cls)}"><div><p class="eyebrow">${e(eyebrow)}</p><h2>${e(title)}</h2></div>${body ? `<p class="section-intro">${e(body)}</p>` : ''}</div>`;
  DM.card = ({ icon = 'chat', title, body, route = '', label = '', cls = '' }) => `<article class="card ${e(cls)}"><span class="icon-disc">${DM.icon(icon)}</span><h3>${e(title)}</h3><p>${e(body)}</p>${route ? DM.link(route, `${e(label)}${DM.icon('arrow')}`, 'text-link') : ''}</article>`;
  DM.accordion = (items, prefix = 'faq', openFirst = false) => `<div class="accordion">${items.map((item, i) => `<details id="${e(prefix)}-${i}"${openFirst && !i ? ' open' : ''}><summary>${e(item.q)}${DM.icon('plus')}</summary><div class="accordion-answer"><p>${e(item.a)}</p></div></details>`).join('')}</div>`;
  DM.steps = (expanded = false) => `<ol class="steps ${expanded ? 'steps-expanded' : ''}">${DM.matchingSteps.map((step, i) => `<li><span class="step-number" aria-hidden="true">${i + 1}</span><div><h3>${e(step.title)}</h3><p>${e(step.body)}</p></div></li>`).join('')}</ol>`;
  DM.callout = (title, body, icon = 'heart', cls = '') => `<aside class="callout ${e(cls)}"><span class="icon-disc">${DM.icon(icon)}</span><div><h3>${e(title)}</h3><p>${body}</p></div></aside>`;
  DM.finalCta = () => `<section class="final-cta"><div class="container final-cta-inner"><div><p class="eyebrow">At your pace. With your questions.</p><h2>A first step.<br>A little more clarity.</h2><p>You do not need a treatment plan to start exploring.</p></div><div>${DM.button('/match')}<p class="cta-caption">Start with what you know. “I’m not sure” is welcome.</p></div></div></section>`;
  DM.header = () => {
    const nav = [['/implants', 'Dental implants'], ['/how-it-works', 'How it works'], ['/costs', 'Costs & options'], ['/about', 'About us']];
    const { variation, route } = DM.state;
    return `<div class="preview-bar"><div class="container preview-inner"><span class="preview-label">Website preview</span><div class="variation-switch" role="group" aria-label="Choose a website variation">${Object.entries(DM.variations).map(([id, v]) => `<button type="button" data-variation="${id}" aria-pressed="${id === variation}"><span class="variation-number">${v.number}</span><span class="variation-long">${e(v.label)}</span><span class="variation-short">${e(v.short)}</span></button>`).join('')}</div></div></div><header class="site-header"><div class="container header-inner">${DM.link('/', DM.logo(), 'brand-home', 'aria-label="Dental Match home"')}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav">${DM.icon('menu')}<span>Menu</span></button><nav class="site-nav" id="site-nav" aria-label="Main navigation">${nav.map(([path, label]) => DM.link(path, e(label), route === path ? 'nav-current' : '', route === path ? 'aria-current="page"' : '')).join('')}${DM.button('/match')}</nav></div></header>`;
  };
  DM.footer = () => `<footer class="site-footer"><div class="container footer-grid"><div class="footer-brand">${DM.link('/', DM.logo(), 'brand-home', 'aria-label="Dental Match home"')}<p>A clearer first step for dental implants and major dental care.</p><span class="footer-location">${DM.icon('location')}Australia-wide matching service</span></div><div><h2>Explore</h2>${DM.link('/implants', 'Dental implants')}${DM.link('/how-it-works', 'How matching works')}${DM.link('/costs', 'Costs & options')}</div><div><h2>Find your starting point</h2>${DM.link('/match', 'Explore my options')}${DM.link('/questions', 'Your questions')}${DM.link('/contact', 'Ask a question')}</div><div><h2>Dental Match</h2>${DM.link('/about', 'About us')}${DM.link('/privacy', 'About this preview')}<p class="footer-role">A matching service.<br>Clinical advice comes from your dentist.</p></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Dental Match</span><span>Interactive website preview. No enquiries are sent.</span></div></footer>`;
  DM.breadcrumb = title => `<div class="container breadcrumb">${DM.link('/', 'Home')}<span aria-hidden="true">/</span><span>${e(title)}</span></div>`;
  DM.pageHero = (eyebrow, title, body, note = '') => `<section class="page-hero"><div class="container page-hero-inner"><div><p class="eyebrow">${e(eyebrow)}</p><h1>${e(title)}</h1><p class="lead">${e(body)}</p></div>${note ? `<div class="page-hero-note">${DM.icon('smile')}<p>${e(note)}</p></div>` : ''}</div></section>`;
  DM.demoNotice = () => `<div class="demo-notice">${DM.icon('book')}<p><strong>Try the enquiry experience.</strong> Use sample details. This preview does not send an enquiry or make a booking.</p></div>`;
  DM.errorSummary = errors => Object.keys(errors).length ? `<div class="error-summary" role="alert" tabindex="-1"><h3>A few details need a look.</h3><ul>${Object.entries(errors).map(([id, text]) => `<li><a href="#field-${e(id)}" data-error-link="${e(id)}">${e(text)}</a></li>`).join('')}</ul></div>` : '';
  DM.field = ({ id, label, type = 'text', value = '', hint = '', error = '', autocomplete = '', required = false, attrs = '', options = null }) => {
    const described = [hint && `hint-${id}`, error && `error-${id}`].filter(Boolean).join(' ');
    const common = `id="field-${e(id)}" name="${e(id)}"${required ? ' required' : ''}${error ? ' aria-invalid="true"' : ''}${described ? ` aria-describedby="${e(described)}"` : ''} ${attrs}`;
    const control = options ? `<select ${common}>${options.map(([val, text]) => `<option value="${e(val)}"${String(value) === val ? ' selected' : ''}>${e(text)}</option>`).join('')}</select>` : type === 'textarea' ? `<textarea ${common} rows="4">${e(value)}</textarea>` : `<input type="${e(type)}" value="${e(value)}" ${common}${autocomplete ? ` autocomplete="${e(autocomplete)}"` : ''}>`;
    return `<div class="form-field"><label for="field-${e(id)}">${e(label)}${required ? '<span class="required-label">Required</span>' : ''}</label>${hint ? `<p class="field-hint" id="hint-${e(id)}">${e(hint)}</p>` : ''}${control}${error ? `<p class="field-error" id="error-${e(id)}">${e(error)}</p>` : ''}</div>`;
  };
  DM.choiceGroup = ({ name, legend, options, value, error = '', multiple = false, compact = false, required = false }) => `<fieldset class="choice-fieldset ${compact ? 'choice-compact' : ''}" id="field-${e(name)}"${error ? ` aria-describedby="error-${e(name)}"` : ''}><legend>${e(legend)}${required ? '<span class="required-label">Required</span>' : ''}</legend><div class="choice-grid">${options.map(option => `<label class="choice-card"><input type="${multiple ? 'checkbox' : 'radio'}" name="${e(name)}" value="${e(option.value)}"${(multiple ? value.includes(option.value) : value === option.value) ? ' checked' : ''}>${option.icon ? DM.icon(option.icon) : ''}<span><strong>${e(option.label)}</strong>${option.detail ? `<small>${e(option.detail)}</small>` : ''}</span><span class="choice-check">${DM.icon('check')}</span></label>`).join('')}</div>${error ? `<p class="field-error" id="error-${e(name)}">${e(error)}</p>` : ''}</fieldset>`;
  DM.progress = step => `<ol class="form-progress" aria-label="Enquiry steps">${['Your starting point', 'Your location', 'Your details', 'Review'].map((label, i) => `<li class="${i < step ? 'complete' : i === step ? 'current' : ''}"${i === step ? ' aria-current="step"' : ''}><span>${i < step ? DM.icon('check') : i + 1}</span><small>${label}</small></li>`).join('')}</ol>`;
  DM.reviewRow = (label, value, step = null) => `<div class="review-row"><dt>${e(label)}</dt><dd>${e(value || 'Not added')}</dd>${step !== null ? `<button type="button" class="text-button" data-edit-step="${step}" aria-label="Edit ${e(label.toLowerCase())}">Edit</button>` : ''}</div>`;
})(window.DentalMatch);
